### PR TITLE
upload changes to GCU-12 and GCU-25

### PR DESCRIPTION
**Pull request by vidwath**
Done with the changes to Top menu bar and modified footer.
Linked contact us page.
http://vidwath.github.io/GopherconDubai.github.io/contact.html

### CODE REVIEW

**Comment by kpvarma** [comment]
@vidwath : Here are my comments

1) Home link in header and footer should take the user to the top of the page 
    <a src="#TOPMENU"  >HOME</a>
    Where TOPMENU is the value of the name attribute for the header element.

2) About Link in header and footer should take the user to the about us section titled "About GopherConDubai 2016". Do the same as above

3) Create a new page called schedule.html by cloning the FAQ page. Just keep heading and remove rest of the contents. Schedule like in header and footer should take the user to this page.

4) Do the same for venue and contact link.

5) Hide Register button for the time being (comment the line)

**Comment by vidwath** [comment]
@kpvarma : I didn't get the First point, "TOPMENU is the value of the name attribute for the header element". Could you please elucidate?

**Comment by vidwath** [comment]
@kpvarma : I got it. Thank you.

**Comment by vidwath** [comment]
http://vidwath.github.io/GopherconDubai.github.io/index.html
Done with the specified changes.

**Comment by kpvarma** [comment]
Every thing looking good.
Can you do one last thing so that I can merge it?
change the name #abt to #about

**Comment by vidwath** [comment]
@kpvarma : Yeah sure.

**Comment by vidwath** [comment]
@kpvarma : Replaced 'abt'. PR sent.

**Comment by kpvarma** [comment]
@vidwath I still see abt 
Please review.

http://vidwath.github.io/GopherconDubai.github.io/index.html#abt

**Comment by vidwath** [comment]
@kpvarma : PR sent. It was updated, i had sent you the old url.

**Pull request merged**
