### PR TITLE
add favicon and new gophercon mascot logo.

### PR DESCRIPTION
**Pull request by vidwath**
@kpvarma : Favicon added and new logo replaced.  http://vidwath.github.io/GopherconDubai.github.io/#about

### CODE REVIEW

**Comment by kpvarma** [comment]
Please add the mascot in image tag and not as a background image for div.'.cd-container_mascot

**Comment by vidwath** [comment]
@kpvarma The mascot is added as image tag and also as background-image in media screen for responsive purpose.

**Comment by kpvarma** [comment]
I dont see any changes in http://vidwath.github.io/GopherconDubai.github.io/
Can you push it to gh-pages?

**Comment by vidwath** [comment]
http://vidwath.github.io/GopherconDubai.github.io/index.html
modified contact us page.(top padding)

**Pull request merged**
