### PR TITLE
GCU-12, Changes to top menu bar.

### PR DESCRIPTION
**Pull request by vidwath**
http://vidwath.github.io/GopherconDubai.github.io/

### CODE REVIEW

**Comment by kpvarma** [comment]
@vidwath I don't see any changes in the link.
Can you help me to understand what changes have you made?
It will be nice if you can add this in the description field while sending PR.

**Comment by vidwath** [comment]
@kpvarma I have made changes to the color on hover and added button like effects to register. You can see it while hovering.

**Comment by kpvarma** [comment]
The changes are looking good.
Can we have the register link look like button by default?
You can change the color of the button when user mouse hover it.
What say @vidwath ?

**Comment by vidwath** [comment]
@kpvarma Yeah, it looks more pleasant. I will change it.

**Comment by vidwath** [comment]
http://vidwath.github.io/GopherconDubai.github.io/
Added button to the register nav tab.

**Pull request merged**
