### PR TITLE
GCU 48

### PR DESCRIPTION
**Pull request by shepleasure**
Created contact section in the home page along with twitter feeds.
http://shepleasure.github.io/GopherconDubai.github.io/#contact

### CODE REVIEW

**Comment by kpvarma** [comment]
@shepleasure can you please change the twitter feed style to the basic one?
The animations are making it look weird.

**Comment by shepleasure** [comment]
Changed to classic

**Comment by kpvarma** [comment]
Can we make it small to fit into the space we have?

**Comment by shepleasure** [comment]
U may check now

**Pull request merged**
