### PR TITLE
Added content to About page

### PR DESCRIPTION
**Pull request by shepleasure**
http://shepleasure.github.io/GopherconDubai.github.io/

### CODE REVIEW

**Comment by kpvarma** [comment]
@shepleasure Have you done the changes we discuss this morning so that I can merge this PR?

**Comment by kpvarma** [comment]
@shepleasure  I dont see them in your gh-pages.

**Comment by shepleasure** [comment]
You can check now

**Comment by kpvarma** [comment]
Looking Better @shepleasure

**Pull request merged**
